# Use Java 21 (or 17 if your project uses that)
FROM eclipse-temurin:25-jdk

WORKDIR /app

# Copy everything
COPY . .

# Build the application
RUN ./mvnw clean package -DskipTests

# Run the jar
CMD ["java", "-jar", "target/*.jar"]
